import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { Outlet, Link, createRootRouteWithContext, useRouter, HeadContent, Scripts } from "@tanstack/react-router";
import { useEffect, type ReactNode } from "react";
import appCss from "../styles.css?url";
import { reportLovableError } from "../lib/lovable-error-reporting";
import { Footer, Header, MobileCallBar } from "@/components/site";
function NotFoundComponent(){return <div className="grid min-h-[60vh] place-items-center px-4 text-center"><div><h1 className="text-7xl font-extrabold">404</h1><p className="mt-3 text-muted-foreground">That patch of ground could not be found.</p><Link to="/" className="button-primary mt-6">Back home</Link></div></div>}
function ErrorComponent({error,reset}:{error:Error;reset:()=>void}){console.error(error);const router=useRouter();useEffect(()=>reportLovableError(error,{boundary:"tanstack_root_error_component"}),[error]);return <div className="grid min-h-[60vh] place-items-center px-4 text-center"><div><h1 className="text-3xl font-extrabold">This page didn’t load</h1><button onClick={()=>{router.invalidate();reset()}} className="button-primary mt-6">Try again</button></div></div>}
export const Route=createRootRouteWithContext<{queryClient:QueryClient}>()({head:()=>({meta:[{charSet:"utf-8"},{name:"viewport",content:"width=device-width, initial-scale=1"},{property:"og:type",content:"website"},{property:"og:image",content:"/og-image.png"},{name:"twitter:card",content:"summary_large_image"}],links:[{rel:"stylesheet",href:appCss},{rel:"preconnect",href:"https://fonts.googleapis.com"},{rel:"preconnect",href:"https://fonts.gstatic.com",crossOrigin:"anonymous"},{rel:"stylesheet",href:"https://fonts.googleapis.com/css2?family=Manrope:wght@400;600;700;800&family=Outfit:wght@500;600;700;800&display=swap"},{rel:"icon",href:"/favicon.svg",type:"image/svg+xml"},{rel:"icon",href:"/favicon.ico",type:"image/x-icon"},{rel:"apple-touch-icon",href:"/apple-touch-icon.png"}]}),shellComponent:RootShell,component:RootComponent,notFoundComponent:NotFoundComponent,errorComponent:ErrorComponent});
function RootShell({children}:{children:ReactNode}){return <html lang="en"><head><HeadContent/></head><body>{children}<Scripts/></body></html>}
function RootComponent(){const {queryClient}=Route.useRouteContext();return <QueryClientProvider client={queryClient}><Header/><main><Outlet/></main><Footer/><MobileCallBar/></QueryClientProvider>}
