import { ArrowRight, CheckCircle2, Leaf, Menu, Phone, X } from "lucide-react";
import { useState, type ReactNode } from "react";
import { business, nav } from "@/lib/site-data";

export function Header() {
  const [open,setOpen]=useState(false);
  return <><div className="bg-forest py-2 text-primary-foreground"><div className="page-shell flex justify-between text-xs font-bold"><span className="hidden sm:block">Free, no-obligation estimates</span></div></div>
  <header className="sticky top-0 z-50 border-b bg-background/95 backdrop-blur"><div className="page-shell grid min-h-18 grid-cols-[minmax(0,1fr)_auto] items-center gap-3">
    <a href="#home" className="flex min-w-0 items-center gap-2"><span className="grid size-9 shrink-0 place-items-center rounded-full bg-primary text-primary-foreground"><Leaf size={18}/></span><span className="truncate font-display text-lg font-extrabold">U&B <span className="text-moss">Landscaping & Tree Service</span></span></a>
    <nav className="hidden items-center gap-6 lg:flex">{nav.map(i=><a key={i.to} href={i.to} className="text-sm font-bold text-muted-foreground transition-colors hover:text-primary">{i.label}</a>)}<a href={business.phoneHref} className="flex items-center gap-2 text-sm font-extrabold"><Phone size={16}/>{business.phone}</a><a href="#contact" className="button-primary">Get a free quote <ArrowRight size={16}/></a></nav>
    <button aria-label={open?"Close menu":"Open menu"} onClick={()=>setOpen(!open)} className="grid size-12 place-items-center rounded-md border lg:hidden">{open?<X/>:<Menu/>}</button>
  </div></header>{open&&<div className="fixed inset-0 z-[60] lg:hidden"><div className="absolute inset-0 bg-foreground/60" onClick={()=>setOpen(false)} aria-hidden="true"/><nav className="drawer-panel absolute right-0 top-0 flex h-full w-[85%] max-w-sm flex-col overflow-y-auto bg-background p-6 shadow-2xl"><div className="flex items-center justify-between"><span className="font-display text-lg font-extrabold">Menu</span><button aria-label="Close menu" onClick={()=>setOpen(false)} className="grid size-12 place-items-center rounded-md border"><X/></button></div><div className="mt-6 grid gap-1">{nav.map(i=><a key={i.to} href={i.to} onClick={()=>setOpen(false)} className="block rounded-md px-3 py-3.5 font-bold hover:bg-muted">{i.label}</a>)}</div><div className="mt-auto grid gap-3 pt-6"><a href={business.phoneHref} onClick={()=>setOpen(false)} className="button-primary w-full"><Phone size={16}/> Call {business.phone}</a><a href="#contact" onClick={()=>setOpen(false)} className="button-primary w-full">Get a free quote</a></div></nav></div>}</>;
}
export function Footer(){return <footer className="bg-forest text-primary-foreground"><div className="page-shell grid gap-10 py-10 md:grid-cols-[1.3fr_.7fr_.8fr] md:py-14"><div><div className="flex items-center gap-2 font-display text-xl font-extrabold"><Leaf/> U&B Landscaping and Tree Service</div><p className="mt-4 max-w-sm text-sm leading-7 opacity-75">Serving Jamaica since 2008. Careful work, honest advice and outdoor spaces made to last.</p><p className="mt-4 text-sm font-bold opacity-80">Serving Jamaica, NY & nearby areas</p></div><div><h3 className="font-bold">Explore</h3><div className="mt-4 grid gap-2">{nav.map(i=><a key={i.to} href={i.to} className="text-sm opacity-75 hover:opacity-100">{i.label}</a>)}</div></div><div><h3 className="font-bold">Start a project</h3><p className="mt-4 text-sm opacity-75">{business.phone}</p><p className="mt-2 text-sm opacity-75">★ 4.3 · 6 Google reviews</p><a href={business.phoneHref} className="button-light mt-5"><Phone size={17}/> Call Now</a></div></div><div className="border-t border-primary-foreground/15 py-5"><div className="page-shell flex flex-col gap-2 text-xs opacity-60 sm:flex-row sm:justify-between"><span>© 2026 U&B Landscaping and Tree Service · Jamaica, NY</span></div></div></footer>}
export function PageHero({eyebrow,title,copy,image}:{eyebrow:string;title:string;copy:string;image:string}){return <section className="relative isolate min-h-[460px] overflow-hidden bg-forest"><img src={image} alt="" className="absolute inset-0 -z-20 h-full w-full object-cover"/><div className="absolute inset-0 -z-10 bg-forest/70"/><div className="page-shell flex min-h-[460px] items-end py-16"><div className="max-w-3xl text-primary-foreground"><p className="mb-4 text-xs font-extrabold uppercase tracking-[.16em] text-secondary">{eyebrow}</p><h1 className="text-balance text-5xl font-extrabold leading-[.98] sm:text-7xl">{title}</h1><p className="mt-6 max-w-2xl text-base leading-7 opacity-85 sm:text-lg">{copy}</p></div></div></section>}
export function QuoteBand(){return <section className="bg-primary py-10 text-primary-foreground"><div className="page-shell flex flex-col items-start justify-between gap-6 md:flex-row md:items-center"><div><p className="text-xs font-bold uppercase tracking-[.15em] text-secondary">Your garden, thoughtfully cared for</p><h2 className="mt-2 text-3xl font-extrabold">Ready for a yard you’re proud of?</h2></div><a href="#contact" className="button-light">Get a free quote <ArrowRight size={17}/></a></div></section>}
export function ContactOptions(){return <div className="flex flex-wrap gap-3"><a href="#contact" className="button-primary">Get a free quote <ArrowRight size={17}/></a><a href={business.phoneHref} className="inline-flex min-h-12 items-center gap-2 rounded-md border border-current px-5 font-extrabold"><Phone size={17}/> Call Now</a></div>}
export function IconStat({icon,number,label}:{icon:ReactNode;number:string;label:string}){return <div className="border-l-2 border-accent pl-5"><div className="text-moss">{icon}</div><strong className="mt-4 block font-display text-3xl">{number}</strong><span className="text-sm text-muted-foreground">{label}</span></div>}

export function QuoteForm(){const[sent,setSent]=useState(false);if(sent)return <div className="w-full rounded-2xl bg-forest p-8 text-primary-foreground shadow-xl"><div className="flex min-h-[380px] flex-col items-center justify-center gap-4 text-center"><CheckCircle2 className="size-14 text-accent"/><h3 className="font-display text-2xl font-extrabold">Thanks!</h3><p className="opacity-80">We’ll be in touch shortly.</p></div></div>;return <div className="w-full rounded-2xl bg-forest p-8 text-primary-foreground shadow-xl"><h3 className="text-center font-display text-lg font-extrabold uppercase tracking-wide">Get a Free Quote</h3><form className="mt-6 space-y-4" onSubmit={e=>{e.preventDefault();setSent(true);}}><div><label className="mb-1.5 block text-sm font-bold">Full Name *</label><input required type="text" autoComplete="name" placeholder="John Smith" className="w-full min-h-12 rounded-lg border-0 bg-white px-4 py-3 text-base text-foreground placeholder:text-muted-foreground/60 focus:outline-none focus:ring-2 focus:ring-accent"/></div><div><label className="mb-1.5 block text-sm font-bold">Phone *</label><input required type="tel" inputMode="tel" autoComplete="tel" placeholder="Example: (917) 417-0195" className="w-full min-h-12 rounded-lg border-0 bg-white px-4 py-3 text-base text-foreground placeholder:text-muted-foreground/60 focus:outline-none focus:ring-2 focus:ring-accent"/></div><div><label className="mb-1.5 block text-sm font-bold">Short message about your needs</label><textarea rows={4} placeholder="Tell us about your yard..." className="w-full resize-none rounded-lg border-0 bg-white px-4 py-3 text-base text-foreground placeholder:text-muted-foreground/60 focus:outline-none focus:ring-2 focus:ring-accent"/></div><button type="submit" className="w-full rounded-full bg-secondary py-4 text-base font-extrabold uppercase tracking-wide text-secondary-foreground transition-transform hover:scale-[1.02]">Send</button></form></div>}
export function MobileCallBar(){return <><div aria-hidden="true" className="h-16 md:hidden" style={{paddingBottom:"env(safe-area-inset-bottom)"}}/><div className="fixed inset-x-0 bottom-0 z-50 grid grid-cols-2 bg-forest shadow-[0_-4px_20px_rgba(0,0,0,0.25)] md:hidden" style={{paddingBottom:"env(safe-area-inset-bottom)"}}><a href={business.phoneHref} className="flex min-h-16 items-center justify-center gap-2 px-4 py-4 text-base font-extrabold text-primary-foreground"><Phone size={18}/> Call Now</a><a href="#contact" className="flex min-h-16 items-center justify-center gap-2 bg-secondary px-4 py-4 text-base font-extrabold text-secondary-foreground"><ArrowRight size={18}/> Free Quote</a></div></>}
