/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiConsultationsRouteImport } from './routes/api/consultations'
import { Route as ApiYardPlanRouteImport } from './routes/api/yard-plan'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConsultationsRoute = ApiConsultationsRouteImport.update({
  id: '/api/consultations',
  path: '/api/consultations',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiYardPlanRoute = ApiYardPlanRouteImport.update({
  id: '/api/yard-plan',
  path: '/api/yard-plan',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/consultations': typeof ApiConsultationsRoute
  '/api/yard-plan': typeof ApiYardPlanRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/consultations': typeof ApiConsultationsRoute
  '/api/yard-plan': typeof ApiYardPlanRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/consultations': typeof ApiConsultationsRoute
  '/api/yard-plan': typeof ApiYardPlanRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/consultations' | '/api/yard-plan'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/consultations' | '/api/yard-plan'
  id: '__root__' | '/' | '/api/consultations' | '/api/yard-plan'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiConsultationsRoute: typeof ApiConsultationsRoute
  ApiYardPlanRoute: typeof ApiYardPlanRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/consultations': {
      id: '/api/consultations'
      path: '/api/consultations'
      fullPath: '/api/consultations'
      preLoaderRoute: typeof ApiConsultationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/yard-plan': {
      id: '/api/yard-plan'
      path: '/api/yard-plan'
      fullPath: '/api/yard-plan'
      preLoaderRoute: typeof ApiYardPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiConsultationsRoute: ApiConsultationsRoute,
  ApiYardPlanRoute: ApiYardPlanRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
